select * from customer limit 20

SELECT column_name 
FROM information_schema.columns 
WHERE table_name = 'customer';
--Altering column names
ALTER TABLE customer
RENAME COLUMN "Purchase Amount (USD)" TO purchase_amount;
ALTER TABLE customer RENAME COLUMN "Previous Purchases" TO previous_purchases;
ALTER TABLE customer RENAME COLUMN "Customer ID" TO customer_id;
ALTER TABLE customer RENAME COLUMN "Review Rating" TO review_rating;
ALTER TABLE customer RENAME COLUMN "Promo Code Used" TO promo_code_used;
ALTER TABLE customer RENAME COLUMN "Subscription Status" TO subscription_status;
ALTER TABLE customer RENAME COLUMN "Payment Method" TO payment_method;
ALTER TABLE customer RENAME COLUMN "Frequency of Purchases" TO frequency_of_purchases;
ALTER TABLE customer
RENAME COLUMN "Discount Applied" TO discount_applied;
ALTER TABLE customer RENAME COLUMN "Item Purchased" TO item_purchased;
ALTER TABLE customer RENAME COLUMN "Shipping Type" TO shipping_type;
ALTER TABLE customer RENAME COLUMN "Category" TO category;
ALTER TABLE customer RENAME COLUMN "Age" TO age;




--Q1. What is total revenue generated by male vs.female customers?
SELECT "Gender", SUM(purchase_amount) AS revenue
FROM customer
GROUP BY "Gender";

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
from customer 
WHERE discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY avg(review_rating) desc
limit 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping?
SELECT shipping_type,
AVG(purchase_amount)
from customer
WHERE shipping_type in ('Standard','Express')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue b/w subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;


--Q6. Which 5 products have the highest percentage of purchases with discount with dicounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Retirning and Loyal based on their total no.of previous purchases,and show the count of each segment.
with customer_type as(
select customer_id, previous_purchases,
CASE
   When previous_purchases = 1 THEN 'New'
   When previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
   Else 'Loyal'
   End as customer_segment
from customer 
)

select   customer_segment , count(*) as "Number of Customers"
from customer_type
group by customer_segment


--Q8. what are the top 3 most purchased products within each category?
with item_count as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
FROM customer 
group by category, 
    item_purchased 
 )

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

SELECT 
    ic.item_rank,
    c.category,
    ic.item_purchased,
    ic.total_orders
FROM item_counts ic
JOIN customer c
    ON ic.item_purchased = c.item_purchased;

SELECT column_name
FROM information_schema.columns
WHERE table_name = 'item_counts';

DROP TABLE IF EXISTS item_counts;

CREATE TABLE item_counts AS
SELECT 
    item_purchased,
    category,
    COUNT(*) AS total_count,
    COUNT(*) AS total_orders,
    RANK() OVER (ORDER BY COUNT(*) DESC) AS item_rank
FROM customer
GROUP BY item_purchased, category;

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status


--Q10. What is the revenue contribution of each group?
select age,
sum(purchase_amount) as total_revenue
from customer
group by age
order by total_revenue desc;

SELECT
    CASE
        WHEN age BETWEEN 0 AND 12 THEN 'Child'
        WHEN age BETWEEN 13 AND 19 THEN 'Teen'
        WHEN age BETWEEN 20 AND 35 THEN 'Young Adult'
        WHEN age BETWEEN 36 AND 55 THEN 'Adult'
        ELSE 'Senior'
    END AS age_group,
    COUNT(*)
FROM customer 
GROUP BY age_group
ORDER BY age_group;

SELECT
    CASE
        WHEN age BETWEEN 18 AND 25 THEN 'Youth'
        WHEN age BETWEEN 26 AND 35 THEN 'Young Adults'
        WHEN age BETWEEN 36 AND 45 THEN 'Adults'
        WHEN age BETWEEN 46 AND 60 THEN 'Middle Age'
        ELSE 'Senior'
    END AS age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


